### ISSUE TITLE
[FTB Beyond v1.11] [MC v1.10.2] Crash when adding DynmapBlockScan

### ISSUE THREAD

**Issue by Zelow79** [webbukkit/DynmapBlockScan#11]
Hello, I am running FTB Beyond version 1.11 (for MC 1.10.2) and I am getting a crash whenever I try to start the server with DynmapBlockScan-3.0-alpha-1-forge-1.10.2.jar in the mods folder. I have tried it with both Dynmap-HEAD-3.x-forge-1.10.2.jar and Dynmap-3.0-alpha-1-forge-1.10.2.jar just to make sure it wasn't a compatibility issue. I checked the crash log folder and there wasn't any logs for the crash. I can upload the console text from start up, but there is a lot and sadly cmd.exe seems to cut some of the top text off.

**Comment by Zelow79** [comment]
Forgot to mention I can get the server to start with JUST Dynmap-3.0-alpha-1-forge-1.10.2 installed and I even got the map to render on localhost:8123

**Comment by DarkSpyro003** [comment]
This appears to be the same crash as #10

**Comment by Chemox** [comment]
As the server doesn't have the proper graphical methods initialised it won't work on the server!
You'll have to run it on the client and copy over the generated files :)

**Comment by mikeprimm** [comment]
Try latest build : should fix this - http://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.0-alpha-1-forge-1.10.2.jar
