### ISSUE TITLE
[ATM3 v4.5 w/Forge2528] Crash when adding BlockScan

### ISSUE THREAD

**Issue by notacompletemoron** [webbukkit/DynmapBlockScan#14]
Mods used, Forge Latest, Crash Report

https://gist.github.com/notacompletemoron/f49af1ab9f558b810a6f9ef12ee50e9c

FML Junk Startup (Too big for Gist. Uploaded to my Dropbox.)

https://www.dropbox.com/s/fy6y4xkr71lbbt5/fml-junk-earlystartup_12112017.7z?dl=0

You will find all crashes, logs, and mods used on the gist.

Additional mods to the regular ATM3 pack are classcachetweaker by Asie and Optifine. I think those are the only additional mods to the pack. Otherwise, it's untouched.

I know the logs say that DynMap is the one that crashed, but I promise you that it works fine as a standalone. The crash only happens when I add BlockScan into the mix.

**Comment by mikeprimm** [comment]
Please try with latest Dynmap release (3.0-alpha-3) or dev builds (http://dynmap.us/builds/dynmap) and with latest DynmapBlockScan builds (http://dynmap.us/builds/DynmapBlockScan/).  This should be fixed with those
