### ISSUE TITLE
Texture filename in lowercase

### ISSUE THREAD

**Issue by aadeg** [webbukkit/DynmapBlockScan#21]
I'm using DynmapBlockScan to generate the *-texture.txt and *-model.txt files to render blocks in a custom mod made by my own.
The problem is that, when DynmapBlockScan generates the *-texture.txt, all the texture path are in lowercase, even if the real texture filename contains capital letters.

For example, this is a line taken from *-texture.txt
```
texture:id=txt0163,filename=assets/forgottenblk/textures/blocks/intonacoluminoso_rosa.png,xcount=1,ycount=1
```
The actual texture path is `assets/forgottenblk/textures/blocks/intonacoLuminoso_rosa.png` (with the capital **L**).

Dynmap version: `Dynmap-3.0-alpha-1-forge-1.10.2`
DynmapBlockScan version: `DynmapBlockScan-3.0-alpha-1-forge-1.10.2`

**Comment by mikeprimm** [comment]
Yep - changed this for 1.10.2 (it actually needs to do it for 1.11 or later).  Give latest build a try - http://dynmap.us/builds/DynmapBlockScan/
