### ISSUE TITLE
1.12.2 Watchdog Kills Start-up

### ISSUE THREAD

**Issue by durand1w** [webbukkit/DynmapBlockScan#23]
Starting up a test server with no Dynmap configuration changes. Startup spams a lot of messages similar to the one's below before crashing.  Appears that the Watchdog process is killing start-up due to the amount of logging being written.  The Tyrbuilders mod below is one that I created and works on a server, but does use several models rather than just blocks.  I don't expect the models to be mapped.  Is it possible to reduce the volume of data logging out since this seems more like a DEBUG level?

Dynmap-3.0-alpha-1-forge-1.12.2
DynmapBlockScan-3.0-alpha-1-forge-1.12.2

[Crash and Startup Logs.zip](https://github.com/webbukkit/DynmapBlockScan/files/2220020/Crash.and.Startup.Logs.zip)

**Comment by Greatone123** [comment]
Could change the tick rate so it disables watchdog. That's what I did to fix the issue.

**Comment by mikeprimm** [comment]
Latest DynmapBlockScan drops the logging spam way down, which should help this.

http://dynmap.us/builds/DynmapBlockScan/

**Comment by durand1w** [comment]
I'm playing with 3.0 Snapshot right now and it started with no issues and is running considerably faster.  In game lag is greatly improved.  Thanks for putting together these changes.  I'll look to take the newer 3.0 release once the fullrender completes.
