### ISSUE TITLE
Another, Different Crash when adding Blockscan to Server

### ISSUE THREAD

**Issue by jjhhgg100123** [webbukkit/DynmapBlockScan#27]
This one gets signifigantly farther in loading than the last version, but still crashes.

[Crash Report](https://pastebin.com/wbFU6NkH)

Running the latest version of FTB Revelations (2.4.1)  - [Mod List](https://www.feed-the-beast.com/projects/ftb-revelation/relations/dependencies)

Running Dynmap-3.0-alpha-3-forge-1.12.2
Running DynmapBlockScan-3.0-alpha-2-forge-1.12.2

**Comment by mikeprimm** [comment]
Please try with latest dev build: NotEnoughIDs wasn't supported before a few days ago, and this looks to be tied to having blocks beyond 4096 (which was part of what needed to be fixed to support NEIDS and JEIDS).  http://dynmap.us/builds/dynmap
