### ISSUE TITLE
Traverse blocks not rendering

### ISSUE THREAD

**Issue by davidsiaw** [webbukkit/DynmapBlockScan#29]
Hello there

Great work on Dynmap. Keep up the good work.

Recently I have been using FTB Revelation 1.12, after adding `DynmapBlockScan-3.0-alpha-2-forge-1.12.2.jar` to the world the Autumnal leaves don't render resulting in this:

![image](https://user-images.githubusercontent.com/874280/47613489-95bdd200-dad3-11e8-86fd-11d4bc7ebeb2.png)

Some of the offending items are as follows:

```
traverse:yellow_autumnal_leaves
traverse:orange_autumnal_leaves
```

This label is taken from here: 

![image](https://user-images.githubusercontent.com/874280/47613502-d61d5000-dad3-11e8-97d5-b499be83ace0.png)

Do I need to do any additional configuration to use DynmapBlockScan? 

<details>

```
Dynmap-3.0-beta-1-forge-1.12.2.jar
DynmapBlockScan-3.0-alpha-2-forge-1.12.2.jar
```

Both of these binaries are available from curse at time of writing.

I have also tried several combinations of:

```
Dynmap-3.0-alpha-3-forge-1.12.2.jar
Dynmap-3.0-beta-1-forge-1.12.2.jar
Dynmap-HEAD-forge-1.12.2.jar
DynmapBlockScan-3.0-alpha-1-forge-1.12.2.jar
DynmapBlockScan-3.0-alpha-2-forge-1.12.2.jar
```

In the server logs a large number of these are spit out:

```
...
"> [10:30:57] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] openblocks:assets/openblocks/models/block/piggy.obj.json : Failed to open model\r\n"
"> [10:30:57] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] thaumcraft:assets/thaumcraft/models/block/thaumatorium.obj.json : Failed to open model\r\n"
"> [10:30:57] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] thaumcraft:assets/thaumcraft/models/block/pillar.obj.json : Failed to open model\r\n"
"> [10:30:57] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] thaumcraft:assets/thaumcraft/models/block/arcane_workbench_charger.obj.json : Failed to open model\r\n"
"> [10:30:57] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] nice:assets/nice/models/block/cylinder.obj.json : Failed to open model\r\n"
"> [10:30:57] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] immersiveengineering:assets/immersiveengineering/models/block/connector/connector_lv.obj.json : Failed to open model\r\n"
"> [10:30:57] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] immersiveengineering:assets/immersiveengineering/models/block/smartmodel/conn_ic2_relay_glass.json : Failed to open model\r\n"
"> [10:31:05] [Server thread/ERROR] [woot]: Woot: Could not load factory loot from /home/minecraft/mcmyadmin/Minecraft/woot/loot.json\r\n"
...
```

Followed by these:

```
"> [10:31:03] [Server thread/WARN] [DynmapBlockScan]: [DynmapBlockScan] {model=dynmapblockscan:forgemodel54377,rotation=X0_Y0}: failed to generate elements for deepresonance:tank[{ values={down=accept, dummy_rcl=1, east=provide, north=none, south=none, up=provide, west=accept},meta=[0]}]\r\n"
"> [10:31:03] [Server thread/WARN] [DynmapBlockScan]: [DynmapBlockScan] {model=dynmapblockscan:forgemodel54366,rotation=X0_Y0}: failed to generate elements for deepresonance:tank[{ values={down=accept, dummy_rcl=1, east=accept, north=provide, south=provide, up=accept, west=provide},meta=[0]}]\r\n"
"> [10:31:03] [Server thread/WARN] [DynmapBlockScan]: [DynmapBlockScan] {model=dynmapblockscan:forgemodel53858,rotation=X0_Y0}: failed to generate elements for deepresonance:tank[{ values={down=none, dummy_rcl=1, east=accept, north=provide, south=none, up=none, west=accept},meta=[0]}]\r\n"
...
```
And these:

```
...
"> [10:33:13] [Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/minecraft/textures/items/bone.png for mod darkutils not found\r\n"
"> [10:33:13] [Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/minecraft/textures/items/egg.png for mod darkutils not found\r\n"
"> [10:33:13] [Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/minecraft/textures/items/wheat.png for mod darkutils not found\r\n"
"> [10:33:13] [Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/minecraft/textures/items/blaze_powder.png for mod darkutils not found\r\n"
"> [10:33:13] [Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/minecraft/textures/items/nether_star.png for mod darkutils not found\r\n"
"> [10:33:13] [Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource 
...
```

I was searching all over for more info about how I would go about installing and troubleshooting DynmapBlockScan, if you could give me a few pointers on how to do that I'll write up some of that info I can write that up in the README and make a PR.

**Comment by Derkades** [comment]
I am having this issue as well on FTB Revelation 2.5.0
![image](https://user-images.githubusercontent.com/15892014/49725674-9027e000-fc6c-11e8-91b5-9a4f261a09fc.png)

**Comment by davidsiaw** [comment]
I was having a brief look at the blockstate stuff but I don't really understand how resources are treated in java and how blockstates are related to that so its taking a while. My small fix idea was to make it so it looks in a local folder for missing blockstate data (plain json) after it searches everywhere.

Would be nice if maintainer could point me in the right direction on this one.

**Comment by mikeprimm** [comment]
I'll try to give it a look - your information looks good enough to get me where I need to be to reproduce it, so hopefully I'll have something useful to say soon :)

**Comment by mikeprimm** [comment]
OK - experimental fix in latest dev build - https://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.0-SNAPSHOT-forge-1.12.2.jar

**Comment by NPutting** [comment]
Was just looking up a solution for this problem as I just grabbed dynmap. Looks like it fixed all of the problems listed above on my map. clear glass is now completely invisible but that looks better than the long green streaks it was making in the alpha-2 build.

**Comment by Derkades** [comment]
Thanks for the quick fix! Traverse blocks display properly now. (And many other mods too probably)

**Comment by davidsiaw** [comment]
Thank you for the fix. I'll close this now so it doesn't continue to pollute the issue list.
