### ISSUE TITLE
DynmapBlockScan Log

### ISSUE THREAD

**Issue by Chemox** [webbukkit/DynmapBlockScan#3]
Sup dude,

Nice work you doing here hope you keep it up. 
Thought this might help you out.
This is the FTBBeyond modpack with BOP added.

Mod loads fine no crashes 👍 
Although multiple errors are present but that is kinda normal in such an early stage.

[https://gist.github.com/Chemox/7b09d710f6013e2810761a44885b3a26](https://gist.github.com/Chemox/7b09d710f6013e2810761a44885b3a26)
Hope it helps you a bit.
Important part is at the end where it starts to scrape for blocks.
Multiblocks seem to be an issue as well.

Keep up the good work!

**Comment by Chemox** [comment]
Obviously I was stupid enough to try and run this on a server ...

Here is a log from a client https://1drv.ms/u/s!AuwFVCq9ljgtw3VcimofAcATBGWv

It spams the logs like crazy with failed to open model errors although it still created the modsupport config files?

**Comment by mikeprimm** [comment]
Yep - thanks for the logs - definitely flag if you encounter a crash.  The logging is more verbose than it should be, ultimately, and there are lots of cases that folks use funky (nondefault) mapping strategies for the block state files for their blocks that will ultimately need to have additional mod-specific data supplied in order to resolve.

**Comment by mminkus** [comment]
I have the same thing. FTB Beyond on 1.10.2, with BoP added. Did you ever get BoP biome textures to work? I ran DynmapBlockScan locally and it generated a ton of texture and model files in dynmap/renderdata/modsupport/ and the biomesoplenty-texture.txt looks reasonable, but I haven't got it to work yet on my server..

**Comment by mikeprimm** [comment]
Latest builds at http://dynmap.us/builds/DynmapBlockScan/ default to a LOAD less log spam, which should help
