### ISSUE TITLE
Error with EnderIO and Chisel

### ISSUE THREAD

**Issue by SnackMix** [webbukkit/DynmapBlockScan#5]
EnderIO conduits didn't seem to load, [view log](https://pastebin.com/raw/6NuTTUk7). Also nothing from Chisel is rendering, it didn't even generate the `modsupport` files for it, [view log](https://pastebin.com/raw/Ay3hsxj5).

- Dynmap-3.0-alpha-1-forge-1.10.2
- DynmapBlockScan-3.0-alpha-1-forge-1.10.2
- Chisel-MC1.10.2-0.0.13.28
- EnderIO-1.10.2-3.1.193
- EnderCore-1.10.2-0.4.1.65-beta

**EDIT**
Okay, so I did another fullrender of the map and no mod blocks are showing. There are files in the `modsupport` folder, I don't know how to validate they are correct though. Does `DynmapBlockScan` need to run from client or server? I'm running it on server and it logs a bunch of stuff like it's working but mod blocks aren't showing on the web.

**Comment by generrosity** [comment]
Runs from the server - doesn't support Chisel as it is too hard - needs support from Chisel to render.
