### ISSUE TITLE
com.google.gson.JsonSyntaxException: duplicate key: particle

### ISSUE THREAD

**Issue by ErikSteiner** [webbukkit/DynmapBlockScan#6]
Hi there,

I was trying to get a working config for Minecraft 1.10.2, in order to see modded blocks in Dynmap. I guess that from what I read, that it isn't possible. So I read about BlockScan and tried it out. Unfortunately it is crashing:
**Forge Server 1.10.2 - 12.18.3.2316
DynmapBlockScan-3.0-alpha-1-forge-1.10.2 and
Dynmap-3.0-alpha-1-forge-1.10.2**

LOG
[error log.txt](https://github.com/webbukkit/DynmapBlockScan/files/1265215/error.log.txt)

**Comment by mikeprimm** [comment]
This should have been fixed a while back - please try latest builds (http://dynmap.us/builds/DynmapBlockScan/).   Also suggest latest dynmap alpha (http://dynmap.us/releases or http://dynmap.us/builds/dynmap) - alpha-3 or latest snapshot
