### ISSUE TITLE
NullPointerException in deserialization

### ISSUE THREAD

**Issue by Mordna** [webbukkit/DynmapBlockScan#64]
Version:  3.4-beta-1-forge-1.12.2

Server crashes when DynmapBlockScan runs (modpack: Divine Journey 2).

Stack trace of crash report:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from DynmapBlockScan (dynmapblockscan)
Caused by: java.lang.NullPointerException
    at org.dynmapblockscan.core.blockstate.Variant$Deserializer.deserialize(Variant.java:131)
    at org.dynmapblockscan.core.blockstate.Variant$Deserializer.deserialize(Variant.java:112)
    ....
```

Cause seems to be a typing error in:
https://github.com/webbukkit/DynmapBlockScan/blob/583ebd9b959c841f44d0a9bf04b02d03f336489b/core/src/main/java/org/dynmapblockscan/core/blockstate/Variant.java#L131

-> 'y' should be 'z'

**Comment by Amgelo563** [comment]
Adding more info into this, you can reproduce this with the [BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether/files/all?filter-game-version=1738749986%3A628) mod, from every version after 0.1.6 (0.1.5 works, .6 doesn't).

Crash report: https://mclo.gs/plDkkIH
Logs: https://mclo.gs/ue8SWCl
