### ISSUE TITLE
DynmapBlockScan server crash

### ISSUE THREAD

**Issue by daPoseidonGuy** [webbukkit/DynmapBlockScan#7]
Launched on "forge-1.10.2-12.18.3.2422-universal"
77 mods
spongeforge-1.10.2-2281-5.2.0-BETA-2597
Foamfix, Surge and betterfps are there.

Crash report:
https://pastebin.com/0ykYdf5S

Will be attempting the same without foamfix surge or betterfps, see how that goes.

Edit; Also probably worth noting DynmapBlockScan kept saying failing to open model for seemingly 90+% of models it tried to load

**Comment by mikeprimm** [comment]
Try latest dev build

**Comment by mrdeadlocked** [comment]
Where would this latest dev build be? DynmapBlockScan-3.0-alpha-1-forge-1.12.1.jar ?

**Comment by Chemox** [comment]
As the server doesn't have the proper graphical methods initialised it won't work on the server!
You'll have to run it on the client and copy over the generated files :)

**Comment by mikeprimm** [comment]
@Chemox These crashes have nothing to do with graphical methods, and DynmapBlockScan (unlike the old DynmapBlockScraper) is not intended to need or require running on the client nor copying of files.

**Comment by mikeprimm** [comment]
DynmapBlockScan will not work with anything before Dynmap 3.0 - please get current Dynmap 3.0 builds here - http://dynmap.us/builds/DynmapForge/

**Comment by Chemox** [comment]
@mikeprimm Oh that is interesting didn't know that. Sorry that I jumped to conclusions to fast. Well very nice work from your side 👍

**Comment by mikeprimm** [comment]
@chemox all good - appreciate the effort - easy point to miss between the two :)
