### ISSUE TITLE
Support for 1.19.3

### ISSUE THREAD

**Issue by Black-Hole** [webbukkit/DynmapBlockScan#75]
Minecraft 1.19.3 introduced several new blocks, which requires a special setting in server.properties to be able to use them. Even without that setting those blocks can be used in any world using third party tools, like WorldEdit.

So it would be nice if DynmapBlockScan could be updated to 1.19.3 to enable Dynmap to render those new experimental vanilla blocks.

See also: https://github.com/webbukkit/dynmap/issues/3897

**Comment by OrangeSniper** [comment]
I agree. I need this too

**Comment by mikeprimm** [comment]
Been out for a while - https://dynmap.us/builds/DynmapBlockScan/
