### ISSUE TITLE
DynmapBlockScan 1.12.1 Server Crash

### ISSUE THREAD

**Issue by mrdeadlocked** [webbukkit/DynmapBlockScan#8]
I'm getting a servercrash trying to load up dynmap + dynmapblockscan. See pastebin. https://pastebin.com/m2Rxc1x5

**Comment by smithnc07** [comment]
I could be wrong in this, however, I believe Block scan needs to be run on the client, not the server. 
After it generates the files, then you move those up to the server renderdata folder.

**Comment by Chemox** [comment]
As the server doesn't have the proper graphical methods initialised it won't work on the server!
You'll have to run it on the client and copy over the generated files :)

**Comment by mikeprimm** [comment]
DynmapBlockScan required Dynmap 3.0 builds: it will not work properly with 2.6  See http://dynmap.us/builds/DynmapForge/ for 3.0 builds
