### ISSUE TITLE
Version of DBS for 1.7.10 missing

### ISSUE THREAD

**Issue by Chaoschaot232** [webbukkit/DynmapBlockScan#83]
Sadly the wiki page for this on the Dynmap Repro was entirely deleted but there was definitely a 1.7.10 DBS Version and instead of hiding it it would be better to re-release it.

It would also help 1.7.10 modded servers with dynmap support to download the files from the community driven DBS Repro. Since it's fully Community driven it shouldn't be any problem to provide any working DBS Version here for it.

Would be nice to see a re-upload here or at http://dynmap.us/builds/DynmapBlockScan/ with the hint that it comes like it is excl. any developing support if not wanted/needed so far. But still ... 1.7.10 is most popular and alive ;)

**Comment by mikeprimm** [comment]
Never was a DynmapBlockScan for v1.7.10, but there was this - https://github.com/webbukkit/DynmapModScraper - old builds are here - https://dynmap.us/builds/DynmapModScraper/ .   Not actively supported, but neither is 1.7.10 dynmap, but feel free to fork as needed
