### ISSUE TITLE
DynmapBlockScan has error at startup - server shutdown

### ISSUE THREAD

**Issue by dwilley83** [webbukkit/DynmapBlockScan#9]
I think a similar error has been posted but my situation may be different.

Running FoolCraft 2.0.1 with Forge-1.10.2-12.18.3.2422.
Using Dynmap-3.0-alpha-1-forge-1.10.2 and DynmapBlockScan-3.0-alpha-1-forge-1.10.2 jars.

This is the error I'm getting. https://pastebin.com/LgaZTyX5

**Comment by Zelow79** [comment]
I think this could be the same error I am getting on the FTB Beyond 1.11 (for MC 1.10.2) pack. I have tried both the Dynmap-3.0-alpha-1-forge-1.10.2.jar and Dynmap-HEAD-3.x-forge-1.10.2. 
Here is my error as well if it can help progress https://pastebin.com/N8MxMEwC.

**Comment by Chemox** [comment]
As the server doesn't have the proper graphical methods initialised it won't work on the server!
You'll have to run it on the client and copy over the generated files :)

**Comment by mikeprimm** [comment]
Try latest build: should be fixed - http://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.0-alpha-1-forge-1.10.2.jar
